### ISSUE TITLE
Traceback (most recent call last): 

### ISSUE THREAD

**Issue by Ankit780966** [itay-bardugo/whatsapp_tracker#10]
when i run cmd 
python whatsapp_tracker/wt_main.py --browser-path /Users/ankitpatel/Downloads/chromedriver --contact "Ankit" --save-path /Users/ankitpatel/Downloads/ --minutes 2 --resolution 5

  File "whatsapp_tracker/wt_main.py", line 9, in <module>
    from whatsapp_tracker.mains.whatsapp_tracker_main import WhatsappTrackerMain
  File "/Users/ankitpatel/Downloads/whatsapp_tracker-master/whatsapp_tracker/mains/whatsapp_tracker_main.py", line 4, in <module>
    from whatsapp_tracker.pipelines.wt_main_pipeline import WTMainPipeline
  File "/Users/ankitpatel/Downloads/whatsapp_tracker-master/whatsapp_tracker/pipelines/wt_main_pipeline.py", line 1, in <module>
    from whatsapp_tracker.mains.whatsapp_tracking_main import WhatsappTrackingMain
  File "/Users/ankitpatel/Downloads/whatsapp_tracker-master/whatsapp_tracker/mains/whatsapp_tracking_main.py", line 1, in <module>
    from whatsapp_tracker.pipelines.wt_tracking_pipeline import WTTrackingPipeline
  File "/Users/ankitpatel/Downloads/whatsapp_tracker-master/whatsapp_tracker/pipelines/wt_tracking_pipeline.py", line 2, in <module>
    from whatsapp_tracker.selenium_whatsapp.selenium_whatsapp_open_contact import SeleniumWhatsappOpenContact
  File "/Users/ankitpatel/Downloads/whatsapp_tracker-master/whatsapp_tracker/selenium_whatsapp/selenium_whatsapp_open_contact.py", line 3, in <module>
    from whatsapp_tracker.bases.selenium_whatsapp_bases.base_selenium_whatsapp_open_contact import BaseSeleniumWhatsappOpenContact
  File "/Users/ankitpatel/Downloads/whatsapp_tracker-master/whatsapp_tracker/bases/selenium_whatsapp_bases/base_selenium_whatsapp_open_contact.py", line 7
    class BaseSeleniumWhatsappOpenContact(BaseSeleniumKeyboard, metaclass=ABCMeta):

**Comment by itay-bardugo** [comment]
Could you plz share the entire backtrace? What is the exception? looks like this part is missing in your log

**Comment by Ankit780966** [comment]
Please check 
ankitpatel@192 whatsapp_tracker-master % python whatsapp_tracker/wt_main.py --browser-path /Users/ankitpatel/Downloads/chromedriver --contact "Ankit" --save-path /Users/itay/Downloads --minutes 2 --resolution 5
Traceback (most recent call last):
  File "whatsapp_tracker/wt_main.py", line 9, in <module>
    from whatsapp_tracker.mains.whatsapp_tracker_main import WhatsappTrackerMain
  File "/Users/ankitpatel/Downloads/whatsapp_tracker-master/whatsapp_tracker/mains/whatsapp_tracker_main.py", line 4, in <module>
    from whatsapp_tracker.pipelines.wt_main_pipeline import WTMainPipeline
  File "/Users/ankitpatel/Downloads/whatsapp_tracker-master/whatsapp_tracker/pipelines/wt_main_pipeline.py", line 1, in <module>
    from whatsapp_tracker.mains.whatsapp_tracking_main import WhatsappTrackingMain
  File "/Users/ankitpatel/Downloads/whatsapp_tracker-master/whatsapp_tracker/mains/whatsapp_tracking_main.py", line 1, in <module>
    from whatsapp_tracker.pipelines.wt_tracking_pipeline import WTTrackingPipeline
  File "/Users/ankitpatel/Downloads/whatsapp_tracker-master/whatsapp_tracker/pipelines/wt_tracking_pipeline.py", line 2, in <module>
    from whatsapp_tracker.selenium_whatsapp.selenium_whatsapp_open_contact import SeleniumWhatsappOpenContact
  File "/Users/ankitpatel/Downloads/whatsapp_tracker-master/whatsapp_tracker/selenium_whatsapp/selenium_whatsapp_open_contact.py", line 3, in <module>
    from whatsapp_tracker.bases.selenium_whatsapp_bases.base_selenium_whatsapp_open_contact import BaseSeleniumWhatsappOpenContact
  File "/Users/ankitpatel/Downloads/whatsapp_tracker-master/whatsapp_tracker/bases/selenium_whatsapp_bases/base_selenium_whatsapp_open_contact.py", line 7
    class BaseSeleniumWhatsappOpenContact(BaseSeleniumKeyboard, metaclass=ABCMeta):
                                                                         ^
SyntaxError: invalid syntax

**Comment by itay-bardugo** [comment]
Is there any chance you are running it on python2?
If so, please switch to
Python3.9 (it may work with any version of python3)

**Comment by Ankit780966** [comment]
it's work with Python3.9 but after scan code chrom crash can you solved it i m using mac os m1 chip latest chrome driver  also i have one question without save number how can we check last seen please reply

**Comment by itay-bardugo** [comment]
1. Is there any log when chrome crashes?btw- it was built in mac m1 so i can confirm its working
2. “Last seen” is not supported metric yet, but you can add a feature request(open an issue) 
3. You must save the number as a contact before. WT is based on your existing contacts.

**Comment by Ankit780966** [comment]
after 2 time crash and login in whatsapp web it's working fine (No log display when it crash ) also in excel sheet this kind of data display

[WTTracker.csv](https://github.com/itay-bardugo/whatsapp_tracker/files/7404208/WTTracker.csv)

**Comment by itay-bardugo** [comment]
When `status` is empty it means your contact was offline
I am Not sure why `name` is also empty
Maybe contact name not found?

**Comment by itay-bardugo** [comment]
@Ankit780966 - still relevant?

**Comment by Ankit780966** [comment]
it solved
